---
name: tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      #
      # setup system
      #
      - name: python install
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: pipenv install
        run:
          python -m pip install --upgrade pipenv wheel
      - name: nodejs install
        uses: actions/setup-node@v4
        with:
          node-version: "15"
      #
      # python dependencies
      #
      - name: python virtualenv cache
        id: cache-pipenv
        uses: actions/cache@v4
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - name: python virtualenv install
        run: pipenv install
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
      #
      # nodejs dependencies
      #
      - name: nodejs modules cache
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - name: nodejs modules install
        run: npm install
        if: steps.cache-npm.outputs.cache-hit != 'true'
      #
      # run tests
      #
      - name: python unit test
        run: pipenv run pytest -v
      - name: cdk synth
        run: |
          export PATH=$PATH:$(pwd)/node_modules/.bin
          pipenv run cdk synth
          test -f cdk.out/manifest.json
